Update bitrise.yml

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -17,6 +17,19 @@ workflows:
         inputs:
         - workflow_id: primary
         - bitrise_config_path: "./bitrise2.yml"
+  test:
+    steps:
+    - script@1.1.6:
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            # fail if any commands fails
+            set -e
+            # debug log
+            set -x
+
+            # write your script here
+            echo "$asdqwe"
   primary:
     description: |
       ## How to get a signed APK
